dependencies:
  - conda-forge::numpy=2.4.6
  - conda-forge::pip=26.2.1
  - conda-forge::python=3.11
  - conda-forge::pandas=3.0.5
  - conda-forge::astropy=8.0.1
  - conda-forge::cython=3.3.0
  - conda-forge::scipy=1.17.1
  - conda-forge::tqdm=4.70.0
  - conda-forge::lmfit=1.3.4
  - pip:
      - matplotlib==3.11.1
      - graphviz==0.21
      - emcee==3.1.6
      - corner==2.3.0
      - orbitize==3.2.1
      - rebound==5.0.1
# 3fd65f021da6ebe9c7fcaec